### ISSUE TITLE
Incorrect response ID - JSONRPCCLIENT

### ISSUE THREAD

**Issue by tjoozey** [PawlicaWeb/CryptoPonzi#17]
```
root@ubuntu-512mb-nyc3-01:~# php /var/www/html/script.php

Parsing transactions...
PHP Fatal error:  Uncaught exception 'Exception' with message 'Incorrect response id (request id: 1, response id: )' in /var/www/html/jsonRPCClient.php:152
Stack trace:
#0 /var/www/html/script.php(39): jsonRPCClient->__call('listtransaction...', Array)
#1 /var/www/html/script.php(39): jsonRPCClient->listtransactions('btc', 100)
#2 {main}
  thrown in /var/www/html/jsonRPCClient.php on line 152

```

JsonRPCClient does not generate transactions after setting up blockchaind RPC API info. Any suggestions on getting a clean install without experiencing this error?

**Comment by OfficialRaider-dev** [comment]
can you give some details about your dev environment? php version, os version, web server, etc
I presume you've set the database up?
I will be attempting an installation tonight on Ubuntu server
